# Generated by Django 5.2.8 on 2025-11-11 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlistings_bids'),
    ]

    operations = [
        migrations.CreateModel(
            name='WacthList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auctionItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acutionItem', to='auctions.auctionlistings')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userWatchlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
